### ISSUE TITLE
Allow download of input file

### ISSUE THREAD

**Issue by dougallj** [decompiler-explorer/decompiler-explorer#51]
If someone shares a decompiler bug repro via dogbolt link, it'd be nice to allow anyone receiving that link to download the input file, so they can reproduce the issue locally.

This would allow dogbolt to be used to report issues to open-source decompiler issue trackers, without unnecessarily restricting the people who can reproduce and fix such issues.

**Comment by CouleeApps** [comment]
We debated this for a bit internally and decided to not provide the option (at least, for now) due to potential issues redistributing binaries that people upload, considering people really like uploading proprietary files. Decompiler maintainers can just contact us for access to the binaries, from which they can download samples if someone submits one.

**Comment by dougallj** [comment]
Thanks! (I figured as much, though I was imagining potential problems with hosting malware.)
